export const projects = [
    {
        id: 0,
        title: 'C&D Tech',
        description: "Our Company's Official Website. Has a Detailed Description of What We Do and Requests Can Be Made as Well.",
        image: '/images/cnd.jpg',
        tags: ['Vue JS', 'Firebase', 'GitHub'],
        github: 'https://github.com/rexdougie/cnd-tech',
        visit: 'https://cnd-tech.web.app/',
    },
    {
        id: 1,
        title: 'Wavma Security',
        description: "Our Company's Official Website. Has a Detailed Description of What We Do and Requests Can Be Made as Well.",
        image: '/images/wavma-sec.jpg',
        tags: ['HTML5', 'CSS', 'Bootstrap', 'Vanilla JS', 'Firebase'],
        github: 'https://github.com/rexdougie/wavma',
        visit: 'https://wavma-security.web.app/',
    },
    {
        id: 2,
        title: 'Prex Interiors',
        description: "Our Company's Official Website. Has a Detailed Description of What We Do and Requests Can Be Made as Well.",
        image: '/images/prex.jpg',
        tags: ['Vanilla JS', 'Firebase', 'HTML5', 'CSS'],
        github: 'https://github.com/rexdougie/prex',
        visit: 'https://prex-interiors-ltd.web.app/',
    },
    {
        id: 3,
        title: 'Cryptapp',
        description: "Our Company's Official Website. Has a Detailed Description of What We Do and Requests Can Be Made as Well.",
        image: '/images/cryptapp.jpg',
        tags: ['React JS', 'Node JS', 'RapidApi', 'Firebase'],
        github: 'https://github.com/rexdougie/cryptapp',
        visit: 'https://cryptapp-41c50.web.app/',
    },
    {
        id: 4,
        title: 'Kenya Prisons',
        description: "Our Company's Official Website. Has a Detailed Description of What We Do and Requests Can Be Made as Well.",
        image: '/images/prisons.jpg',
        tags: ['Vanilla JS', 'HTML5', 'Bootstrap', 'Firebase'],
        github: 'https://github.com/rexdougie/',
        visit: 'https://kenya-prisons-sports.web.app/',
    },
    {
        id: 5,
        title: 'Kikao64 Cafe',
        description: "Our Company's Official Website. Has a Detailed Description of What We Do and Requests Can Be Made as Well.",
        image: '/images/kikao64.jpg',
        tags: ['React Native', 'React', , 'Firebase'],
        github: 'https://github.com/rexdougie/kikao64',
        visit: 'https://kikao64.web.app/',
    },
]

export const TimeLineData = [
    { year: 2019, text: 'Started my journey' },
    { year: 2020, text: 'Worked On Petty Personal Projects to Hone My Skills' },
    { year: 2021, text: 'Worked With Different Companies' },
    { year: 2022, text: 'The Journey Continues ...' },
]